name: Deploy with Ansible

on:
  push:
    branches:
      - feature-ansible-workflow  # Trigger this action on push to the 'feature-ansible-workflow' branch
  pull_request:
    branches:
      - main  # Trigger this action on pull requests to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up SSH keys for accessing the server
      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Store your SSH private key in GitHub secrets

      # Add SSH known hosts to avoid host key verification error
      - name: Add SSH known hosts
        run: |
          ssh-keyscan -H 13.61.147.207 >> ~/.ssh/known_hosts
          # ssh-keyscan -H 51.20.131.60 >> ~/.ssh/known_hosts

      # Install Ansible
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      # Run the Ansible playbook
      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory.ini playbook.yml
